github.com:
    users:
        Xer0Zer0:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: Xer0Zer0
